export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content?: string;
  author: string;
  authorRole?: string;
  date: string;
  readTime: string;
  category: string;
  featured: boolean;
  icon: string;
  headerImage?: string;
  views: number;
  likes: number;
  comments: number;
  tags: string[];
}

export const allBlogPosts: BlogPost[] = [
  {
    slug: 'neurondb',
    title: 'NeuronDB a PostgreSQL AI Extension',
    excerpt: 'PostgreSQL extension for vector search, ML inference, and RAG. Includes HNSW indexing, GPU acceleration, 10 distance metrics, and pgvector compatibility.',
    content: 'NeuronDB is a PostgreSQL extension. Provides vector search, machine learning inference, GPU acceleration, and hybrid retrieval. For semantic search, RAG applications, and recommendation systems.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-20',
    readTime: '22 min read',
    category: 'Technical',
    featured: true,
    icon: 'neurondb',
    headerImage: '/blog/neurondb/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['AI', 'Vector Database', 'Machine Learning', 'Semantic Search', 'RAG', 'PostgreSQL']
  },
  {
    slug: 'neurondb-semantic-search-guide',
    title: 'Semantic Search Over Text with NeuronDB',
    excerpt: 'Semantic search over text using NeuronDB. Includes examples, SQL queries, and code. Guide to building document search systems, RAG pipelines, and hybrid search.',
    content: 'Guide to implementing semantic search with NeuronDB. Includes examples, SQL queries, RAG pipeline construction, hybrid search techniques, and optimization strategies.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-19',
    readTime: '25 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/neurondb-semantic-search-guide/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['NeuronDB', 'Semantic Search', 'RAG', 'Vector Search', 'PostgreSQL', 'Tutorial', 'AI']
  },
  {
    slug: 'neurondb-vectors',
    title: 'Vectors in PostgreSQL',
    excerpt: 'Vector operations, indexing, and similarity search in PostgreSQL with NeuronDB. Guide with SQL queries and results. Covers HNSW indexing, distance metrics, quantization, and performance optimization.',
    content: 'Guide to working with vectors in PostgreSQL using NeuronDB. Covers vector types, operations, distance metrics, indexing strategies, quantization, and performance optimization with SQL queries and results.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-21',
    readTime: '30 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/neurondb-vectors/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['NeuronDB', 'Vectors', 'Vector Search', 'HNSW', 'Distance Metrics', 'PostgreSQL', 'Tutorial', 'AI', 'Indexing']
  },
  {
    slug: 'neurondb-mcp-server',
    title: 'MCP Server: Model Context Protocol Explained',
    excerpt: 'MCP Server (Model Context Protocol) guide. What it is, how it works, integration with Claude Desktop, known MCP servers, and NeuronMCP implementation. How MCP enables AI assistants to access external tools and resources.',
    content: 'MCP Server architecture, protocol implementation, Claude Desktop integration, popular MCP servers, and NeuronMCP. How the Model Context Protocol enables AI assistants to access external tools and data sources.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-22',
    readTime: '28 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/neurondb-mcp-server/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['MCP', 'ModelContextProtocol', 'ClaudeDesktop', 'NeuronMCP', 'AI', 'PostgreSQL', 'VectorDatabase', 'MachineLearning', 'RAG', 'OpenSource', 'NeuronDB']
  },
  {
    slug: 'rag-complete-guide',
    title: 'RAG: Retrieval-Augmented Generation With PostgreSQL',
    excerpt: 'RAG (Retrieval-Augmented Generation) guide with examples, SQL queries, and implementation patterns. How to build RAG systems with document retrieval, context building, LLM integration, and response generation.',
    content: 'RAG architecture, implementation patterns, SQL examples, and NeuronDB integration. How to build RAG systems with document processing, embedding generation, similarity search, context building, and response generation.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-23',
    readTime: '35 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/rag-complete-guide/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['RAG', 'RetrievalAugmentedGeneration', 'LLM', 'VectorSearch', 'SemanticSearch', 'NeuronDB', 'PostgreSQL', 'AI', 'MachineLearning', 'DocumentRetrieval', 'KnowledgeBase']
  },
  {
    slug: 'rag-architectures-ai-builders-should-understand',
    title: 'RAG Architectures AI Builders Should Understand',
    excerpt: 'Core RAG architecture patterns: basic, conversational, filtered, adaptive, hypothesis-driven, agent-driven, and graph-based RAG. When to use each and what trade-offs matter in production.',
    content: 'Core RAG patterns and how to choose between them. Covers conversational RAG, filtering/reranking, adaptive retrieval, agent-driven workflows, graph-based retrieval, and operational realities.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2026-01-01',
    readTime: '18 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/rag-architectures-ai-builders-should-understand/header.svg?v=1',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['RAG', 'RAGArchitectures', 'LLM', 'VectorSearch', 'SemanticSearch', 'GraphRAG', 'AgenticAI', 'ProductionAI']
  },
  {
    slug: 'agentic-ai',
    title: 'Agentic AI: Guide to Autonomous AI Agents',
    excerpt: 'Agentic AI systems guide. Agent architecture, planning, tool use, memory systems, and autonomous task execution. Implementation using NeuronDB and NeuronAgent with code examples.',
    content: 'Agentic AI architecture, planning systems, tool execution, memory management, state machines, and implementation patterns. How to build autonomous agents using NeuronDB and NeuronAgent with code examples.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-24',
    readTime: '40 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/agentic-ai/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['AgenticAI', 'AutonomousAgents', 'AIAgents', 'AgentArchitecture', 'ToolUse', 'Planning', 'MemorySystems', 'NeuronDB', 'NeuronAgent', 'PostgreSQL', 'LLM', 'RAG', 'VectorSearch', 'MachineLearning', 'AI']
  },
  {
    slug: 'postgresql-vector-database',
    title: 'PostgreSQL as a Vector Database',
    excerpt: 'Using PostgreSQL as a vector database. How PostgreSQL with NeuronDB extension works as a vector database with HNSW indexing, similarity search, and production capabilities.',
    content: 'PostgreSQL vector database architecture, performance benchmarks, indexing strategies, query patterns, and migration approaches. How PostgreSQL with NeuronDB works as a vector database solution.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-25',
    readTime: '35 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/postgresql-vector-database/header.svg?v=8',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['PostgreSQL', 'VectorDatabase', 'NeuronDB', 'VectorSearch', 'HNSW', 'SQL', 'Database', 'AI', 'SemanticSearch', 'Production', 'Indexing']
  },
  {
    slug: 'ai-with-database-on-prem',
    title: 'AI With Data On-Premises',
    excerpt: 'Deploying AI workloads with databases on-premises. On-premises AI infrastructure, data sovereignty, security, performance, and implementation with NeuronDB. Architecture patterns, deployment strategies, and examples.',
    content: 'On-premises AI infrastructure, data sovereignty, security architecture, performance optimization, deployment strategies, and implementation patterns. How to deploy NeuronDB and AI workloads on-premises with control over data and infrastructure.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-26',
    readTime: '38 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/ai-with-database-on-prem/header.svg?v=7',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['OnPremises', 'AIInfrastructure', 'DataSovereignty', 'PrivateAI', 'EnterpriseAI', 'SelfHosted', 'NeuronDB', 'PostgreSQL', 'Security', 'Compliance', 'EdgeAI', 'HybridCloud']
  },
  {
    slug: 'hitl-workflows-approval-systems-neuronagent',
    title: 'Human-in-the-Loop (HITL) Workflows: Implementing Approval Systems with NeuronAgent',
    excerpt: 'Complete guide to implementing Human-in-the-Loop (HITL) workflows and approval systems with NeuronAgent. Learn workflow engine architecture, approval state machines, and real-world implementation patterns.',
    content: 'HITL workflows combine automated agent execution with human decision points. NeuronAgent provides a DAG-based workflow engine with built-in HITL support. Workflows can pause execution, request human approval, wait for decisions, and resume based on approval outcomes.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-27',
    readTime: '32 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/hitl-workflows-approval-systems-neuronagent/header.svg?v=1',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['HITL', 'HumanInTheLoop', 'ApprovalSystems', 'WorkflowEngine', 'NeuronAgent', 'AgentWorkflows', 'WorkflowAutomation', 'NeuronDB', 'PostgreSQL', 'AIAgents', 'AgenticAI']
  },
  {
    slug: 'agent-memory-systems-long-term-short-term',
    title: 'Agent Memory Systems: Long-Term vs Short-Term Memory in AI Agents',
    excerpt: 'Complete guide to implementing agent memory systems. Learn the differences between long-term and short-term memory, retrieval strategies, and implementation patterns with NeuronDB and NeuronAgent.',
    content: 'AI agents need memory to maintain context across interactions. Memory enables agents to remember past conversations, learn from experience, and build knowledge over time. This guide explains agent memory architecture, covers short-term and long-term memory patterns, and details implementation with NeuronDB and NeuronAgent.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-02-28',
    readTime: '35 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/agent-memory-systems-long-term-short-term/header.svg?v=1',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['AgentMemory', 'LongTermMemory', 'ShortTermMemory', 'AgentMemorySystems', 'MemoryRetrieval', 'SemanticMemory', 'NeuronAgent', 'NeuronDB', 'PostgreSQL', 'VectorSearch', 'AIAgents', 'AgenticAI']
  },
  {
    slug: 'integrating-claude-desktop-neurondb-setup-guide',
    title: 'Integrating Claude Desktop with NeuronDB: Complete Setup Guide',
    excerpt: 'Step-by-step guide to integrating Claude Desktop with NeuronDB using NeuronMCP. Learn installation, configuration, testing, and common workflows for using NeuronDB tools in Claude Desktop.',
    content: 'Claude Desktop is Anthropic\'s desktop application for Claude AI. It supports Model Context Protocol (MCP) servers that enable Claude to access external tools and data sources. NeuronMCP is an MCP server implementation that provides Claude Desktop with access to NeuronDB\'s vector search, ML inference, and RAG capabilities.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-03-01',
    readTime: '28 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/integrating-claude-desktop-neurondb-setup-guide/header.svg?v=1',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['ClaudeDesktop', 'NeuronMCP', 'MCPServer', 'ClaudeIntegration', 'NeuronDB', 'ModelContextProtocol', 'PostgreSQL', 'VectorSearch', 'AIAssistants']
  },
  {
    slug: 'neurondb-vs-pgvector',
    title: 'NeuronDB vs pgvector: Feature Comparison and Migration Guide',
    excerpt: 'Complete comparison of NeuronDB and pgvector features, performance benchmarks, and step-by-step migration guide. Learn when to use each solution and how to migrate from pgvector to NeuronDB.',
    content: 'PostgreSQL users have two main options for vector search: pgvector and NeuronDB. Both extensions add vector capabilities to PostgreSQL, but they differ significantly in features, performance, and use cases. This guide compares NeuronDB and pgvector, provides performance benchmarks, and includes a complete migration guide.',
    author: 'NeuronDB Team',
    authorRole: 'Core Developers',
    date: '2025-03-02',
    readTime: '30 min read',
    category: 'Technical',
    featured: false,
    icon: 'neurondb',
    headerImage: '/blog/neurondb-vs-pgvector/header.svg?v=1',
    views: 0,
    likes: 0,
    comments: 0,
    tags: ['NeuronDB', 'pgvector', 'VectorDatabase', 'PostgreSQL', 'VectorSearch', 'AIDatabase', 'DatabaseComparison', 'MigrationGuide', 'VectorExtension', 'PostgreSQLExtension']
  }
];

